# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='images',
            field=models.ImageField(upload_to='/webpage/static/webpage/images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='/webpage/static/webpage/images'),
        ),
    ]
