# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20161101_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='/static/webpage/images/DP.jpg', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='images',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='notes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
