# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_auto_20161101_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
