# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0009_auto_20161105_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='data',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.profile'),
        ),
        migrations.AlterField(
            model_name='images',
            name='user3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.profile'),
        ),
    ]
