# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_auto_20161105_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=200)),
                ('massage', models.CharField(max_length=200)),
                ('user4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.profile')),
            ],
        ),
    ]
