# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_massage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='user4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
